### ISSUE TITLE
Feature to register for notification by center

### ISSUE THREAD

**Issue by jithin-zachariah** [abizerlokhandwala/Cowin-Notification-Service#17]
Since the API already provides us with the center data, It would be better if there is a feature to register for a specific center[s] rather than an entire district.

**Comment by abizerlokhandwala** [comment]
Hey @jithin-zachariah !
We had thought of this usecase, though one issue users would face is:
1. Lets say, a user registers for 3 centers nearby their home.
2. After a few days, a new center opens up that is closer to their location.
3. The user would have no intuitive way of knowing that they can subscribe to that new center.
Issue #4 is being worked on to solve this problem, so that users receive alerts for nearby centers only.

**Comment by jithin-zachariah** [comment]
Cool that would be fine
