### ISSUE TITLE
Pincode 'centers near us' feature

### ISSUE THREAD

**Issue by abizerlokhandwala** [abizerlokhandwala/Cowin-Notification-Service#4]
1. Find a data source with all pincodes present in India (https://data.gov.in/sites/default/files/all_india_PO_list_without_APS_offices_ver2_lat_long.csv).
2. Through Google Maps Geolocation API (or any similar API) find lat long coordinates for each pincode.
3. Devise a method to preprocess and store nearby pincodes together (10km, 25km, 50km radiuses). To be discussed.

**Comment by Saunved** [comment]
@abizerlokhandwala Is it possible to cache the results of each operation or would you rather precompute the nearest centers for each pincode and fetch those directly from the database?

**Comment by abizerlokhandwala** [comment]
@Saunved currently, our workflow is: 
Every 10 seconds: 
1. Detect new centers with available vaccination slots for a district.
2. Find all verified users that have subscribed to that district, age group, and vaccine.
3. Queue them up to receive a notification.

In step 2, based on the center's pincode, we can find out all users within an X km radius, and only queue them up for notifications.

With the above points in mind, my perspective is:
1. Caching would be a great idea, but it might lead to a few new users missing out on notifs until the cache expires.
2. Precomputing nearest centers would not be a good idea as we don't have an exhaustive list of centers, new centers can come up anytime.
3. Though, we can precompute pincode pair distances for a district, and store only the ones within a particular radius.
4. I would prefer having online queries where we calculate distances on the go between centers and user's pincodes, we can conduct experiments with the above pincode dataset and check if this is efficient and truly scalable.

**Comment by Saunved** [comment]
Thanks for explaining the current flow. 

Do the users set the distance in km from their location / pincode when they create a subscription? What options do they get here? (10km, 25km, 50km?)

Also, if we precompute centers <-> pincode distances, I believe this will be easier to work with and much faster overall. The total pincodes to compare against each center can be limited by using the **first three characters in a pincode**.

**Sample algo for precomputing**
```
For each center of centers
  locations <- match all pincodes with pincode.substring(0, 3) === center.pincode.substring(0,3)
  center.tenkm <- match all pincodes within 10k of center
  center.twentyfivekm <- copy center.tenkm + match all remaining pincodes for within 25k of center
  center.fiftykm <- copy center.twentyfivekm + match all remaining pincodes for within 50k of center
Exit
```
Let me know if you spot any issues with doing this.
I am not very sure about the first 3 characters rule, because **some districts could be less than 50km apart, which might cause issues. In that case, we can precompute against the first two characters of the pincode**. This still causes issues with districts on state boundaries, but since crossing states is not allowed, we can safely ignore this concern.

**Comment by abizerlokhandwala** [comment]
@Saunved currently we do not have user pincode information, we aim to get that data before we go live with this feature.
You are right, we can use the above algorithm to precompute all center distances, I believe all districts have centers with the same 2 digit pincode prefix.
Though, whenever a new center opens up, we would have to dynamically calculate and store distances in that case.

**Comment by Shreyansh97** [comment]
The approach we can take for this is first we need to validate if the pincodes dataset is accurate and complete, otherwise we can rely on the Google APIs for getting lat long for the centres and subscribers. We could also look into embedding Google Maps on the website which would allow users to select accurate locations instead of pincodes. 
Whatever method we choose to go ahead with, we would store the latitude, longitude and distance preference for subscribers and evaluate whenever a new session at a center is available.

**Comment by oasisvali** [comment]
@abizerlokhandwala I wanted to help out with preparing the data to enable this feature. Based on the discussion above, my understanding is that we are looking for a data dump where each entry looks like this:

```json
{
  "pincode": "411010",
  "proximity": [
    { "pincode": "411011", "distance": "0.24" },
    { "pincode": "411012", "distance": "0.67" },
    { "pincode": "411020", "distance": "1.56" },
    # a list of pincodes by increasing order of distance, until a cut-off distance
  ],
  "latitude": "",
  "longitude": "",
  "district": ""
}
```

I have identified this dataset: https://data.gov.in/node/6818285 as the most up-to-date list of PIN codes. It contains 19279 unique PIN codes. Passing each through the google maps geocode API will provide the lat/long e.g.:

https://maps.googleapis.com/maps/api/geocode/json?address=411040&key=<apiKey>

For ~20k PIN codes this will be easily within the free tier credits provided by Google Cloud. ($5/1K request, $200 free credit)

Then we can use the haversine distance calculation to calculate a distance matrix. The matrix can then be imported into the database to build further subsets as required (within 5 km, within 10km etc.)

I can provide the script so that it can be run periodically on the updated PIN code list (it is updated monthly on data.gov.in). The script only uses the geocode API for new PIN codes.

If this approach sounds good to you, I can make a PR with the script and an initial data dump

**Comment by abizerlokhandwala** [comment]
Hey @oasisvali! Long time! Hope you're doing well.

This approach would work well, though we would like to first confirm if most of the center pincodes given by Co-win do exist in our dataset, otherwise we can look into an alternative dataset (http://www.geonames.org/export/zip/IN.zip), which has lat/long information too, though this was published in 2015.

I understand that you are presently out of India, we can provide you with our APIs which act as a proxy to Cowin's APIs to get you center information (pincodes mainly), or you can set up a VPN on your end and use Cowin's APIs directly.

Once we're confident that most of Cowin's centers' pincodes are present in our dataset, we can go ahead with the above data dump, and store these mappings in our database. We should be able to skip out on online queries for calculating distances in this case, which might lead to efficiency issues as the number of users scale.

@Shreyansh97 what are your thoughts on this?

**Comment by oasisvali** [comment]
@abizerlokhandwala sounds good! hope you're doing well too :)

I can use a VPN to query the Cowin API. Let me write a validation script to get a set of PIN codes from the Cowin `sessions` API and see how many of those PIN codes exist in the data set I'm using.

**Comment by abizerlokhandwala** [comment]
@oasisvali do use the `calendarByDistrict` API to fetch the pincodes, instead of the `findByDistrict` API, as the former won't return centers that have 0 slots.

**Comment by oasisvali** [comment]
@abizerlokhandwala Update based on some validation:

I used the `calendarByDistrict` API to fetch the pinCodes, From the set of 756 Districts (and 22194 centers) listed on Cowin I found 6361 unique PIN codes. When I cross-referenced them against the data.gov.in dataset, 106 of these were missing (failure rate 1.6%)

I cross referenced this against the geonames Dataset as well (which contains 19097 unique PIN codes) and found that it was missing only 82 out of the 6361 PIN codes returned by Cowin. (failure rate 1.2%)

If this sort of failure rate is acceptable, and we have a fallback, then I can proceed. Let me know which dataset you think I should prefer.

**Comment by abizerlokhandwala** [comment]
@oasisvali Let's go with the data.gov.in dataset, as it gets updated every month and also has a higher number of pincodes than the other one. Also, lets calculate the lat/long data for the missing 106 pincodes to create the distance matrix. This seems good to go ahead with.
